layout: layout.html

routes:
  GET /: index.html
  GET /auth/github/callback: login.html

pages:
  chat.html:
    user: GET user?access_token={{cookies.token}}

  index.html:
    orgs: GET user/orgs?access_token={{cookies.token}}
    chat: chat.html


